### ISSUE TITLE
请问如何将一个block的map，按照20面对称性展开

### ISSUE THREAD

**Issue by zququ** [homurachan/Block-based-recontruction#1]
您好，

我这里有个一个病毒颗粒的一个block map的.mrc文件，我想将它展开成一个完整的20面体对称性，请问如何实现？

**Comment by homurachan** [comment]
See https://github.com/homurachan/Block-based-recontruction/wiki . Sorry I didn't notice there had been an issue.

**Comment by zququ** [comment]
> See https://github.com/homurachan/Block-based-recontruction/wiki . Sorry I didn't notice there had been an issue.

Thanks!
